### ISSUE TITLE
Performance Monitoring (psutil) block incorrect CPU

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/metrics#4]
Happening on Windows server. Output of psutil block is different than what is seen on Windows resource monitor. Needs investigation.

Screenshot shows nio reported CPU on left, and Windows Server Manager reported CPU on right.

https://www.dropbox.com/s/qva05omy881drb1/Screenshot%202014-10-06%2014.38.36.png?dl=0

**Comment by tyoungNIO** [comment]
We found that this machine and PSUtil don't play together well, the windows machine returns binary cpu percentages alternating between 0 and 100% for each core. This results in an overall percentage that is not representative of reality. Our current understanding is that this is a limitation of the hardware and PSUtil, that is to say the block is returning the data it's getting and is operating normally.
