### ISSUE TITLE
I want the ability to get process information for running nio services.

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/metrics#5]
The current metrics block does not get info for individual processes. 

I want a block that can be passed a signal with a process id and then get an output signal with info about the process. That way you can build a service that first uses the nio api to get a process id and then pass that to his block to get memory info. 

Another option is to build a block that does that all in one. You can tell it what services you want to check (or all services that are not stopped) and emit process information at a configured interval.

**Comment by oleiman** [comment]
I think the former of the two options is more general. I'm going to go from there.
